core/urls.py
from xml.etree.ElementInclude import include
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('superadmin/', admin.site.urls),
    path('pages/',include('pages.urls')),
    path('',include('accounts.urls')),
    path('report/',include('report.urls')),
    path('summernote/',include('django_summernote.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

report/urls.py
from django.urls import path
from .import views
from report.managements.views import  *

urlpatterns = [
    # path('page/',views.report_page,name='report_page'),
    path('',views.report,name='report'),
    path('<int:pk>/update',views.update_report,name='update_report'),
    path('<int:pk>/delete',views.delete_report,name='delete_report'),
    path('data/chart/',views.data_chart,name='data_chart'),

    # Admin 
    path('admin/',admin,name='superadmin'),
    path('admin/data/',data_analysis,name='data_analysis'),
    path('report_feedback_message_replied/',report_feedback_message_replied,name='report_feedback_message_replied'),
    
]

report/models.py
from django.db import models
from accounts.models import User
from feedback.models import Feedback


class TypeOfIncident(models.Model):
    name = models.CharField(max_length=250)
    def __str__(self):
        return self.name

    class Meta:
        
        verbose_name = 'Type Of  Incident'
        verbose_name_plural = 'Type Of Incidents'

class Report(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    type_of_incident = models.ForeignKey(TypeOfIncident,on_delete=models.CASCADE)
    descriptions = models.TextField()
    status = models.IntegerField(default=0)
    photo = models.FileField(upload_to='photo/incident')
    feedback_reply = models.TextField(blank=True) 
    date_reported = models.DateTimeField(auto_now_add=True)
    date_of_incident = models.DateTimeField()
    
    def __str__(self):
        return f'{self.user.first_name} {self.user.last_name}'

    class Meta:
        verbose_name = 'report'
        verbose_name_plural = 'reports'

report/forms.py
from .models import Report
from django_summernote.widgets import SummernoteWidget, SummernoteInplaceWidget
from django import  forms


class ReportForm(forms.ModelForm):
    # date_of_incident = forms.DateField(widget = forms.SelectDateWidget)
    class Meta:
        model = Report
        fields = '__all__'
        exclude = ('user','feedback','status',)
        widgets = {
            'user':forms.TextInput(attrs={
                'type':'hidden',
            }),
            'descriptions':forms.TextInput(attrs={
                'type':'text',
                'class':'form-control',
                'placeholder':'descriptions'
            }),
            'type_of_incident':forms.Select(attrs={
                'type':'select',
                'class':'form-control',
                'placeholder':'type of incident'
            }),
            'photo':forms.FileInput(attrs={
                'type':'file',
                'class':'form-control',
                'placeholder':'photo'
            }),
            'date_of_incident':forms.DateTimeInput(attrs={
                'type':'date',
                'class':'form-control',
                'placeholder':'date of incident'
            }),
            
        }    


class UpdateReportForm(forms.ModelForm):
    class Meta:
        model = Report  
        fields = '__all__'
        exclude = ('feedback','status')
        widgets = {
            'user':forms.TextInput(attrs={
                'type':'hidden',
            }),
        }    

    def __init__(self, *args, **kwargs):
        super(UpdateReportForm, self).__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs['class'] = 'form-control'       

report/managements/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from accounts.models import *
from ..models import  *
from django.core.paginator import Paginator
from django.views.decorators.csrf import csrf_exempt

def admin(request):
    if request.user.is_superadmin != True:
        return HttpResponse('This page is for Super Admin')
    else:
        total_report = Report.objects.count()
        total_done_report = Report.objects.filter(status=1).count()
        total_ignore_report = Report.objects.filter(status=2).count()
        reports = Report.objects.all().order_by('-date_reported')

        # page pagination
        paginator = Paginator(reports, 25)
        page = request.GET.get('page')
        paged_reports = paginator.get_page(page)
        context = {
            'reports':paged_reports,
            'total_report':total_report,
            'total_ignore_report':total_ignore_report,
            'total_done_report':total_done_report,
        }
    return render(request,'report/managements/admin.html',context)


# Superadmin Dashboard 
def data_analysis(request):
    if request.user.is_superadmin != True:
        return HttpResponse('This page is for Super Admin')
    else:
        total_report = Report.objects.count()
        total_done_report = Report.objects.filter(status=1).count()
        total_ignore_report = Report.objects.filter(status=2).count()
        reports = Report.objects.all().order_by('-date_reported')

        # page pagination
        paginator = Paginator(reports, 25)
        page = request.GET.get('page')
        paged_feedbacks = paginator.get_page(page)
        context = {
            'reports':paged_feedbacks,
            'total_report':total_report,
            'total_ignore_report':total_ignore_report,
            'total_done_report':total_done_report,
        }
    return render(request,'report/managements/data.html',context)



@csrf_exempt
def report_feedback_message_replied(request):
    if not request.user.is_superadmin == True:
        return HttpResponse('You are not allow to view this page')
    else:

        id = request.POST.get('id')
        feedback_reply = request.POST.get('message')

        try:
            report_feedback = Report.objects.get(id=id)

            report_feedback.feedback_reply = feedback_reply
            report_feedback.save()
            return HttpResponse('True')
        except:
            return HttpResponse('False')    

report/views.py
from django.http import HttpResponse
from django.shortcuts import redirect, render
from pytz import country_names
from accounts.models import User
from .models import Report, TypeOfIncident
from .forms import ReportForm, UpdateReportForm
from django.contrib.auth.decorators import login_required
from django.contrib import  messages
from django.views.decorators.csrf import csrf_exempt

#Plotly Graph chart
# from plotly.offline import plot
# import pandas as pd
# import plotly.express as px

# User to make report of any accident or incidents
@login_required
def report(request):
    if request.method == 'POST':
        form = ReportForm(request.POST,request.FILES)
        if form.is_valid():
            descriptions = form.cleaned_data['descriptions']
            photo = form.cleaned_data['photo']
            date_of_incident = form.cleaned_data['date_of_incident']
            type_of_incident = form.cleaned_data['type_of_incident']
            user = User.objects.get(id=request.user.id)
            report = Report.objects.create(user=user,type_of_incident=type_of_incident,descriptions=descriptions,photo=photo,date_of_incident=date_of_incident)
            
            report.save()

            print('form save')
            messages.success(request,'Report sent successfully')
            return redirect('dashboard')
        print('form invalid')
        messages.error(request, 'Failed to send Report')    
    else:
        form = ReportForm()        
    context = {
        'form':form
    }        
    return render(request,'report/report.html',context)


# update individul report 
def update_report(request,pk):
    if not request.user:
        return HttpResponse('Log in to access the page')
    else:    
        report = Report.objects.get(id=pk)
        if request.method == 'POST':
            form = UpdateReportForm(request.POST,request.FILES,instance=report)

            if form.is_valid():
                form.save()
                print('Success')
                messages.success(request,'Report updated successfully')
                return redirect('dashboard')
            else:
                print('Failed')  
                messages.error(request,'Fail to update report')  
                return redirect('dashboard')
        else:
            form = UpdateReportForm(instance=report)
        context = {
            'form':form,
            'report':report,
        }        
        return render(request, 'report/update.html',context)


#Delete individual report
@login_required(login_url='login')    
def delete_report(request,pk):
    if not request.user:
        return HttpResponse('Log in to access this page')
    else:    
        report = Report.objects.get(id=pk)
        if request.method == 'POST':
            report.delete()
            print('Success')
            messages.success(request, 'Report deleted successfully')
            return redirect('dashboard')
        else:
            print('Failed')  
            # return redirect('delete_report')  
        context = {
            'report':report
        }
    return render(request,'report/delete.html',context)    


# Data Analysis 
def data_chart(request):
    if not request.user:
        return HttpResponse('Log in to access page')
    else:
        count = Report.objects.filter(user=request.user).count()
        counts = Report.objects.filter(user=request.user)
       
            
        done_report = Report.objects.filter(user=request.user,status=1).count()
        in_process_report = Report.objects.filter(user=request.user,status=0).count()
        ignore_report = Report.objects.filter(user=request.user,status=2).count()
        report_data = [
            {
                'Total Report':count,
                'Total Done Report':done_report,
                'Total Ignore Report':ignore_report
            }

        ]  
        # df = pd.DataFrame(report_data)

        # fig = px.histogram(df,x = ['Total Done Report','Total Ignore Report'],y='Total Report',title="Report Data Analysis", barmode='group', height=600)

        # gantt_plot = plot(fig, output_type='div')     
        context = {
            # 'graph':gantt_plot,
            'count':count,
            'done_report':done_report,
            'in_process_report':in_process_report,
            'ignore_report':ignore_report
        }
    return render(request, 'report/data_analysis.html',context)

templates/report/data_analysis.html
{% extends "shared/layout.html" %}
{% load static %}

{% block body %}
{% autoescape off %}
    {{ graph }}
{% endautoescape %}


{% endblock body%}

{% block script %}
<canvas id="myChart" width="80" height="50"></canvas>
<script>
const ctx = document.getElementById('myChart').getContext('2d');
const myChart = new Chart(ctx, {
    type: 'bar',
    data: {
        labels: ['Total Report', 'Total Done Report','Total Ignore Report'],
        datasets: [{
            label: 'Report Data Analysis',
            data: ['{{count}}','{{done_report}}','{{ignore_report}}'],
            backgroundColor: [
                '#F1A109',
                '#40FA2E',
                
                '#F60804',
                
            ],
            
            borderWidth: 0,
            barPercentage:0.3,
        }]
    },
    options: {
        scales: {
            y: {
                beginAtZero: true
            }
        }
    }
});
</script>
{% endblock script %}

templates/report/delete.html
{% extends "shared/layout.html" %}
{% load static %}

{% block body %}
<form action="{% url 'delete_report' report.id %}" method="POST" >
    {% csrf_token %}
    <fieldset>
        <legend>Delete Report</legend>
           <h2>Are you sure you want to delete the post "{{ report.id }}"</h2>
      
        <div class="button">
            <button type="submit"> Yes, DELETE</button>
            <a href="{% url 'dashboard'  %}">cancel</a>
        </div>
    </fieldset>
</form>

{% endblock body %}

templates/report/report.html
{% extends "shared/layout.html" %}
{% load static %}

{% block body %}
 <!-- Showcase -->
 <section id="showcase">
  <div class="container text-center">
    <div class="home-search p-5">
      <div class="overlay p-5">
        <h1 class="display-4 mb-4">
          REPORT CASES
        </h1>
        <p class="lead">Tell us your report in details and we will get back to you in few minutes</p>
        <div class="search">
          <form action="{% url 'report' %}" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
              {% if user.is_authenticated %}
                <input type="hidden" name="user" value="{{user.id}}">
              {% endif %}
            <!-- Form Row 1 -->
            <div class="form-row">
              <div class="col-md-4 mb-3">
                <label class="sr-only">Type of Incident</label>
                {{ form.type_of_incident }}
                {{ form.type_of_incident.errors }}
              </div>

              <div class="col-md-8 mb-3">
                <label class="sr-only">Description</label>
                {{ form.descriptions | safe }}
                
              </div>
            </div>
            <!-- Form Row 2 -->
            <div class="form-row">
              <div class="col-md-6 mb-3">
                <label class="sr-only">Photos</label>
                {{ form.photo }}
                {{ form.photo.errors }}
              </div>
              <div class="col-md-6 mb-3">
                <label class="sr-only">Date of incident</label>
                {{ form.date_of_incident }}
                {{ form.date_of_incident.errors }}
              </div>
            </div>
            <input type="hidden" name="next" value="{{ next }}">
            <button class="btn btn-secondary btn-block mt-4" type="submit" value="submit" >Make Report</button>
          </form>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock body %}

templates/report/update.html
{% extends "shared/layout.html" %}
{% load static %}
{% block static %}
<link rel="stylesheet" href="{% static 'css/update.css' %}">      
{% endblock static %}
{% block body %}
{% include "partials/_breadcrumb.html" %}

 <!-- Showcase -->
 <section id="showcase">
    <div class="container text-center">
      <div class="home-search p-5">
        <div class="overlay p-5">
          <h1 class="display-4 mb-4">
            REPORT CASES
          </h1>
          <p class="lead">Tell us your report in details and we will get back to you in few minutes</p>
          <div class="search">
            <form  action="{% url 'update_report' report.id %}" method="POST" > 
              {% csrf_token %}
              <input type="hidden" name="user" id="id_user" value="{{ report.user.id }}">
              <!-- Form Row 1 -->
              <div class="form-row">
                <div class="col-md-4 mb-3">
                  <label class="sr-only">Type of Incident</label>
                  {{ form.type_of_incident }}
                  {{ form.type_of_incident.errors }}
                </div>
  
                <div class="col-md-8 mb-3">
                  <label class="sr-only">Description</label>
                  {{ form.descriptions }}
                  {{ form.descriptions.errors }}
                </div>
              </div>
              <!-- Form Row 2 -->
              <div class="form-row">
                <div class="col-md-6 mb-3">
                  <label class="sr-only">Photos</label>
                  {{ form.photo }}
                  {{ form.photo.errors }}
                </div>
                <div class="col-md-6 mb-3">
                  <label class="sr-only">Date of incident</label>
                  {{ form.date_of_incident }}
                  {{ form.date_of_incident.errors }}
                </div>
              </div>
              <input type="hidden" name="next" value="{{ next }}">
              <button class="btn btn-secondary btn-block mt-4" type="submit" value="submit" >Save changes</button>
            </form>
          </div>
        </div>
      </div>
    </div>
  </section>
{% endblock body %}